name: Linux arm64 Release Build

on:
  push:
    branches:
      - release  # Trigger the workflow on push events to the main branch

jobs:
  build:
    runs-on: ubuntu-22.04  # Explicitly set the version for better ARM64 support
    strategy:
      matrix:
        architecture: [arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'  # Python 3.11 for ARM

      - name: Install wx
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev  python3-wxgtk4.0 # GTK3 for wx compatibility

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executable
        run: pyinstaller --clean main.spec

      - name: Move in support data files for runtime
        run: cp unknown_badge.png dist/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tritime-linux-arm64
          path: dist/**

      - name: Cache Build Output
        uses: actions/cache@v3
        with:
          path: ./dist/
          key: linux-arm64-app-build-${{ github.ref_name }}-${{ github.sha }}
          enableCrossOsArchive: true
