name: Windows x64 Release Build - Azure Enabled

on:
  push:
    branches: [ azure-release ]
  pull_request:
    branches: [ azure-release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./

    - name: Move in support data files for runtime
      run: cp unknown_badge.png dist/windows/

    - uses: actions/upload-artifact@v4
      with:
        name: tritime-win64
        path: ./dist/windows

    - name: Cache Build Output
      uses: actions/cache@v3
      with:
        path: ./dist/windows/
        key: windows-app-build-azure-${{ github.ref_name }}-${{ github.sha }}
        enableCrossOsArchive: true
